blank_issues_enabled: false
contact_links:
  - name: Metalworks Discord
    url: https://discord.gg/GwGTMknXhp
    about: If you want direct communication and faster answers, please join our discord!
